routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login-admin');
})->middleware('guest');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/profile','UserController@edit');
Route::post('/profile','UserController@update');

Route::middleware(['auth'])->group(function () {

    Route::resource('admin/customer','CustomerController');

    Route::resource('admin/kategori-produk','KategoriProdukController');

    Route::resource('admin/produk','ProdukController');

    Route::get('admin/transaksi','TransaksiController@index')->name('transaksi.index');

    Route::get('admin/transaksi/create','TransaksiController@create')->name('transaksi.create');

    Route::post('admin/transaksi','TransaksiController@store')->name('transaksi.store');

    Route::get('admin/transaksi/{id}','TransaksiController@show')->name('transaksi.detail');

    Route::get('admin/transaksi/{id}/edit','TransaksiController@edit')->name('transaksi.edit');

    Route::patch('admin/transaksi/{id}','TransaksiController@update')->name('transaksi.update');

    Route::get('admin/transaksi/{id}/delete','TransaksiController@destroy')->name('transaksi.destroy');

    //ajax-transaction
    Route::get('transaksi/get-customer/{id}','TransaksiController@getCustomer');

    Route::get('transaksi/get-produk-by-kategori/{id}','TransaksiController@getProduk');

    Route::post('admin/transaksi/get-produk','TransaksiController@getDetailProduk');

    //report
    Route::get('transaksi/report','ReportController@transaksiController');
    


});

app/Models/KategoriProduk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class KategoriProduk extends Model
{
    protected $table = 'm_kategori_produk';

    protected $guarded = ['id'];
}

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    protected $table = 'm_produk';

    protected $guarded = ['id'];

    public function category()
    {
        return $this->belongsTo(KategoriProduk::class,'kategori_id');
    }
}

app/Http/Controllers/KategoriProdukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\KategoriProduk;
use DB;

class KategoriProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // dd('aaa');
        $kategoriProuduk = KategoriProduk::orderBy('id','DESC')->get();
        return view('admin.produk.kategori-produk.index',compact('kategoriProuduk'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.produk.kategori-produk.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());

        $this->validate($request,[
            'name' => 'required|max:30'
        ]);

        KategoriProduk::create($request->all());

        return redirect()->route('kategori-produk.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategoriProuduk = KategoriProduk::where('id',$id)->first();
        return view('admin.produk.kategori-produk.update',compact('kategoriProuduk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());

        $this->validate($request,[
            'name' => 'required|max:30'
        ]);

        KategoriProduk::where('id',$id)->update($request->except('_token','_method'));

        return redirect()->route('kategori-produk.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cekData = DB::table('m_produk')->where('kategori_id',$id)->count();

        if($cekData > 0 ){
            return redirect()->route('kategori-produk.index')->with('message','Data tidak Bisa dihapus karena sudah dipakai untuk Produk');
        }

        KategoriProduk::where('id',$id)->delete();
        return redirect()->route('kategori-produk.index')->with('message-success','Data berhasil dihapus');
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\Models\Produk;
use App\Models\KategoriProduk;
use Illuminate\Http\Request;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataProduk = Produk::with(['category'])->orderBy('id','DESC')->get();
        // dd($dataProduk);
        return view('admin.produk.index',compact('dataProduk'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $code = $this->setCodeProduk();
        $kategoriProduk = KategoriProduk::orderBy('name')->get();
        return view('admin.produk.create',compact('kategoriProduk'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());

        $this->validate($request,[
            'code' => 'required|max:30|unique:m_produk',
            'name' => 'required|max:30',
            'kategori_id' => 'required',
        ]);

        Produk::create($request->all());

        return redirect()->route('produk.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dataProduk = Produk::where('id',$id)->first();
        $kategoriProduk = KategoriProduk::orderBy('name')->get();

        return view('admin.produk.update',compact('dataProduk','kategoriProduk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());

        $this->validate($request,[
            'code' => 'required|max:30|unique:m_produk,code,'.$id,
            'name' => 'required|max:30',
            'kategori_id' => 'required',
        ]);

        Produk::where('id',$id)->update($request->except('_token','_method'));

        return redirect()->route('produk.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cekData = DB::table('d_transaksi')->where('produk_id',$id)->count();

        if($cekData > 0 ){
            return redirect()->route('produk.index')->with('message','Data tidak Bisa dihapus karena sudah dipakai untuk transaksi');
        }

        Produk::where('id',$id)->delete();
        return redirect()->route('produk.index')->with('message-success','Data berhasil dihapus');
    }

    protected function setCodeProduk()
    {
        $getLastCode = DB::table('m_produk')->select('id')->orderBy('id', 'desc')->pluck('id')->first();

        $getLastCode = $getLastCode +1;

        $nol = null;
        if(strlen($getLastCode) == 1){$nol = "000000";}elseif(strlen($getLastCode) == 2){$nol = "00000";
        }elseif(strlen($getLastCode) == 3){$nol = "0000";}elseif(strlen($getLastCode) == 4){$nol = "000";
        }elseif(strlen($getLastCode) == 5){$nol = "00";}elseif(strlen($getLastCode) == 6){$nol = "0";
        }else{$nol = null;}

        //set value request code
        return 'PRD'.$nol.$getLastCode;
    }

    public function Development()
    {
        # code...
    }
}

resources/views/admin/produk/kategori-produk/create.blade.php
@extends('adminlte.app')


@section('htmlheader_title', 'Data Kategori Produk')
@section('contentheader','Data Kategori Produk')


@section('customcss')
<link rel="stylesheet" href="{{ URL::asset('css/select2-bootstrap.min.css') }}">
<link rel="stylesheet" href="{{URL::asset('plugins/select2.min.css')}}">
<style media="screen">
    .required{
        color: red;
        font-size: 12px;
        font-weight: bold;
    }
</style>
@stop

@section('main-content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-info">

            <form action="{{ route('kategori-produk.store') }}" method="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                {{ method_field('post') }}
                <div class="box-body">
                    @include('admin.displayerror')
                    <div class="form-group">
                        <label class=" control-label">Nama Kategori <span class="required">*</span></label>
                        <input type="text" name="name" class="form-control" placeholder="Nama Kategori..." maxlength="30">
                    </div>
                </div>

                <div class="box-footer">
                    <div class="pull-right">
                        <a href="{{ route('kategori-produk.index')}}" class="btn btn-info">Kembali</a>
                        <input type="reset" class="btn btn-danger" value="Batal">
                        <input  type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@stop
@section('scripts')
<script type="text/javascript" src="{{URL::asset('/plugins/select2.full.min.js')}}"></script>
<script type="text/javascript">
    var langId = "{{asset('vendor/select2/js/i18n/id.js')}}";
    $(document).ready(function () {
        $("#select2").select2();
    })
</script>
@stop

resources/views/admin/produk/kategori-produk/index.blade.php
@extends('adminlte.app')


@section('htmlheader_title', 'Data Kategori Produk')
@section('contentheader','Data Kategori Produk')



@section('customcss')
    <link rel="stylesheet" href="{{URL::asset('css/datatables.min.css')}}">
@stop

@section('main-content')
    <div class="box box-primary">
        <div class="box-body">
            <div class="">
                <a href="{{ route('kategori-produk.create') }}" class="btn btn-success btn-md">
                    <i class="fa fa-plus"></i> Tambah Data
                </a>
            </div>
            @include('admin.displayerror')
            <table class="table table-striped table-hover table-responsive" id="table">
                <thead>
                    <tr>
                        <th style="width:15%">No.</th>
                        <th style="width:70%">Nama</th>
                        <th class="nosort">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i = 1 ?>
                    @foreach ($kategoriProuduk as $key => $value)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $value->name }}</td>
                            <td>
                                <a href="{{ route('kategori-produk.edit',$value->id) }}" class="btn btn-primary btn-sm"><span class="fa fa-pencil"></span></a>

                                <a href="{{ route('kategori-produk.destroy',$value->id) }}" class="btn btn-danger btn-sm" onclick="event.preventDefault(); document.getElementById('delete-form').submit();">
                                        <span class="fa fa-trash"></span>
                                </a>

                                <form id="delete-form" action="{{ route('kategori-produk.destroy',$value->id) }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                        {{method_field('DELETE')}}
                                    <input type="submit" value="delete" style="display: none;">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

@stop

@section('scripts')
    <script type="text/javascript" src="{{URL::asset('/js/jquery.dataTables.min.js')}}"></script>
    <script type="text/javascript" src="{{URL::asset('/js/datatables.bootstrap.min.js')}}"></script>
    <script type="text/javascript">
        $('#table').DataTable({
            "columnDefs": [
            { "orderable": false, "targets": 4 }
          ]
        });
    </script>
@stop

resources/views/admin/produk/kategori-produk/update.blade.php
@extends('adminlte.app')


@section('htmlheader_title', 'Data Kategori Produk')
@section('contentheader','Data Kategori Produk')


@section('customcss')
<link rel="stylesheet" href="{{ URL::asset('css/select2-bootstrap.min.css') }}">
<link rel="stylesheet" href="{{URL::asset('plugins/select2.min.css')}}">
<style media="screen">
    .required{
        color: red;
        font-size: 12px;
        font-weight: bold;
    }
</style>
@stop

@section('main-content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-info">

            <form action="{{ route('kategori-produk.update',$kategoriProuduk->id) }}" method="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                {{ method_field('put') }}
                <div class="box-body">
                    @include('admin.displayerror')
                    <div class="form-group">
                        <label class=" control-label">Nama Kategori <span class="required">*</span></label>
                        <input type="text" name="name" class="form-control" placeholder="Nama Kategori..." maxlength="30" value="{{$kategoriProuduk->name}}">
                    </div>
                </div>

                <div class="box-footer">
                    <div class="pull-right">
                        <a href="{{ route('kategori-produk.index')}}" class="btn btn-info">Kembali</a>
                        <input type="reset" class="btn btn-danger" value="Batal">
                        <input  type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@stop
@section('scripts')
<script type="text/javascript" src="{{URL::asset('/plugins/select2.full.min.js')}}"></script>
<script type="text/javascript">
    var langId = "{{asset('vendor/select2/js/i18n/id.js')}}";
    $(document).ready(function () {
        $("#select2").select2();
    })
</script>
@stop