routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login-admin');
})->middleware('guest');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/profile','UserController@edit');
Route::post('/profile','UserController@update');

Route::middleware(['auth'])->group(function () {

    Route::resource('admin/customer','CustomerController');

    Route::resource('admin/kategori-produk','KategoriProdukController');

    Route::resource('admin/produk','ProdukController');

    Route::get('admin/transaksi','TransaksiController@index')->name('transaksi.index');

    Route::get('admin/transaksi/create','TransaksiController@create')->name('transaksi.create');

    Route::post('admin/transaksi','TransaksiController@store')->name('transaksi.store');

    Route::get('admin/transaksi/{id}','TransaksiController@show')->name('transaksi.detail');

    Route::get('admin/transaksi/{id}/edit','TransaksiController@edit')->name('transaksi.edit');

    Route::patch('admin/transaksi/{id}','TransaksiController@update')->name('transaksi.update');

    Route::get('admin/transaksi/{id}/delete','TransaksiController@destroy')->name('transaksi.destroy');

    //ajax-transaction
    Route::get('transaksi/get-customer/{id}','TransaksiController@getCustomer');

    Route::get('transaksi/get-produk-by-kategori/{id}','TransaksiController@getProduk');

    Route::post('admin/transaksi/get-produk','TransaksiController@getDetailProduk');

    //report
    Route::get('transaksi/report','ReportController@transaksiController');
    


});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $table = 'm_customer';

    protected $guarded = ['id'];
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\Models\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataCustomer = Customer::orderBy('id','DECS')->get();

        return view('admin.customer.index',compact('dataCustomer'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->name);

        $this->validate($request,[
            'name' => 'required|max:30',
            'telephone' => 'max:13',
        ]);

        Customer::create($request->all());

        return redirect()->route('customer.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = Customer::where('id',$id)->first();
        return view('admin.customer.update',compact('customer'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());

        $this->validate($request,[
            'name' => 'required|max:30',
            'telephone' => 'max:13',
        ]);

        Customer::where('id',$id)->update($request->except('_token','_method'));

        return redirect()->route('customer.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $cekDataCustomer = DB::table('t_transaksi')->where('customer_id',$id)->count();
        if($cekDataCustomer > 0 ){
            return redirect()->route('customer.index')->with('message','Data tidak Bisa dihapus karena sudah dipakai untuk transaksi');
        }

        Customer::where('id',$id)->delete();
        return redirect()->route('customer.index')->with('message-success','Data berhasil dihapus');
    }
}

resources/views/admin/customer/create.blade.php
@extends('adminlte.app')


@section('htmlheader_title', 'Data Customer')
@section('contentheader','Data Customer')


@section('customcss')
<link rel="stylesheet" href="{{ URL::asset('css/select2-bootstrap.min.css') }}">
<link rel="stylesheet" href="{{URL::asset('plugins/select2.min.css')}}">
<style media="screen">
    .required{
        color: red;
        font-size: 12px;
        font-weight: bold;
    }
</style>
@stop

@section('main-content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-info">

            <form action="{{ route('customer.store') }}" method="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                {{ method_field('post') }}
                <div class="box-body">
                    @include('admin.displayerror')
                    <div class="form-group">
                        <label class=" control-label">Nama Customer <span class="required">*</span></label>
                        <input type="text" name="name" class="form-control" placeholder="Nama Customer..." maxlength="30 required">
                    </div>

                    <div class="form-group">
                        <label class="control-label">Telpon <span class="required">*</span></label>
                        <input type="text" name="telephone" class="form-control" placeholder="Telpon..." maxlength="13" onkeypress='return event.charCode >= 48 && event.charCode <= 57' required>
                    </div>

                    {{--  <div class="form-group">
                        <label class="control-label">Alamat <span class="required">*</span></label>
                        <textarea name="address" class="form-control" placeholder="Alamat..." required></textarea>
                    </div>  --}}
                </div>

                <div class="box-footer">
                    <div class="pull-right">
                        <a href="{{ route('customer.index')}}" class="btn btn-info">Kembali</a>
                        <input type="reset" class="btn btn-danger" value="Batal">
                        <input  type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@stop
@section('scripts')
<script type="text/javascript" src="{{URL::asset('/plugins/select2.full.min.js')}}"></script>
<script type="text/javascript">
    var langId = "{{asset('vendor/select2/js/i18n/id.js')}}";
    $(document).ready(function () {
        $("#select2").select2();
    })
</script>
@stop

resources/views/admin/customer/index.blade.php
@extends('adminlte.app')


@section('htmlheader_title', 'Data Customer')
@section('contentheader','Data Customer')



@section('customcss')
    <link rel="stylesheet" href="{{URL::asset('css/datatables.min.css')}}">
@stop

@section('main-content')
    <div class="box box-primary">
        <div class="box-body">
            <div class="">
                <a href="{{ route('customer.create') }}" class="btn btn-success btn-md">
                    <i class="fa fa-plus"></i> Tambah Data
                </a>
            </div>
            @include('admin.displayerror')
            <table class="table table-striped table-hover table-responsive" id="table">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Nama Customer</th>
                        {{--  <th>Alamat</th>  --}}
                        <th>Telpon</th>
                        <th class="nosort">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i = 1 ?>
                    @foreach ($dataCustomer as $key => $value)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $value->name }}</td>
                            {{--  <td>{{ $value->address }}</td>  --}}
                            <td>{{ $value->telephone }}</td>
                            <td>
                                <a href="{{ route('customer.edit',$value->id) }}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Ubah"><span class="fa fa-pencil"></span></a>

                                <a href="{{ route('customer.destroy',$value->id) }}" class="btn btn-danger btn-sm" onclick="event.preventDefault(); document.getElementById('delete-form').submit();" data-toggle="tooltip" data-placement="top" title="Hapus" >
                                        <span class="fa fa-trash"></span>
                                </a>

                                <form id="delete-form" action="{{ route('customer.destroy',$value->id) }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                        {{method_field('DELETE')}}
                                    <input type="submit" value="delete" style="display: none;">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

@stop

@section('scripts')
    <script type="text/javascript" src="{{URL::asset('/js/jquery.dataTables.min.js')}}"></script>
    <script type="text/javascript" src="{{URL::asset('/js/datatables.bootstrap.min.js')}}"></script>
    <script type="text/javascript">
        $('#table').DataTable({
            "columnDefs": [
            { "orderable": false, "targets": 3 }
         ]
        });

        
        
    </script>
@stop

resources/views/admin/customer/update.blade.php
@extends('adminlte.app')


@section('htmlheader_title', 'Data Customer')
@section('contentheader','Data Customer')


@section('customcss')
<link rel="stylesheet" href="{{ URL::asset('css/select2-bootstrap.min.css') }}">
<link rel="stylesheet" href="{{URL::asset('plugins/select2.min.css')}}">
<style media="screen">
    .required{
        color: red;
        font-size: 12px;
        font-weight: bold;
    }
</style>
@stop

@section('main-content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-info">

            <form action="{{ route('customer.update',$customer->id) }}" method="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                {{ method_field('put') }}
                <div class="box-body">
                    @include('admin.displayerror')
                    <div class="form-group">
                        <label class=" control-label">Nama Customer <span class="required">*</span></label>
                        <input type="text" name="name" class="form-control" placeholder="Nama Customer..." maxlength="30"value="{{ $customer->name }}">
                    </div>

                    <div class="form-group">
                        <label class="control-label">Telpon</label>
                        <input type="text" name="telephone" class="form-control" placeholder="Telpon..." maxlength="13" onkeypress='return event.charCode >= 48 && event.charCode <= 57'value="{{ $customer->telephone }}">
                    </div>

                    {{--  <div class="form-group">
                        <label class="control-label">Alamat</label>
                        <textarea name="address" class="form-control" placeholder="Alamat...">{{ $customer->address }}</textarea>
                    </div>  --}}
                </div>

                <div class="box-footer">
                    <div class="pull-right">
                        <a href="{{ route('customer.index')}}" class="btn btn-info">Kembali</a>
                        <input type="reset" class="btn btn-danger" value="Batal">
                        <input  type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@stop
@section('scripts')
<script type="text/javascript" src="{{URL::asset('/plugins/select2.full.min.js')}}"></script>
<script type="text/javascript">
    var langId = "{{asset('vendor/select2/js/i18n/id.js')}}";
    $(document).ready(function () {
        $("#select2").select2();
    })
</script>
@stop